import {cleanup, fireEvent, render, screen, waitFor} from '@testing-library/react';
import {afterEach, beforeEach, expect, it, vi} from 'vitest';
import UnderstandHelp from '@/components/UnderstandHelp';
import {fiveNewExamples, splitExplanation} from '@/lib/explanation-examples';
import {buildSituationHtml, readSituation} from '@/lib/situation';
const mocks = vi.hoisted(()=>({add:vi.fn(), cards:vi.fn(), find:vi.fn(), more:vi.fn(), save:vi.fn()}));
vi.mock('@/lib/storage',()=>({addCard:mocks.add,getCardsByDeck:mocks.cards}));
vi.mock('@/lib/learning-help',()=>({findExplanations:mocks.find,requestMoreExamples:mocks.more,saveExplanation:mocks.save,markExplanationUsed:vi.fn(),requestExplanation:vi.fn()}));
vi.mock('sonner',()=>({toast:{success:vi.fn(),error:vi.fn(),info:vi.fn()}}));
vi.mock('@/components/ui/drawer',()=>({Drawer:({children}:any)=><div>{children}</div>,DrawerContent:({children}:any)=><div>{children}</div>,DrawerHeader:({children}:any)=><div>{children}</div>,DrawerTitle:({children}:any)=><h2>{children}</h2>}));
const explanation={id:'e',selectedText:'Try',sentence:'Try again.',title:'Try',quickMeaning:'Tentar',conceptKey:'examples-v2:try',explanation:'Try = tentar.\n• Try again. → Tente novamente.\n👉 tried = passado.',cardFront:'Try',cardBack:'',useCount:1};
const examples=['Try this.','Try the soup.','I will try.','She tried yesterday.','Try another way.'].map(english=>({english,portuguese:'Tradução'}));
beforeEach(()=>{vi.clearAllMocks();mocks.cards.mockResolvedValue([]);mocks.add.mockResolvedValue({id:'new'});mocks.find.mockResolvedValue({exact:explanation,related:[]});mocks.save.mockImplementation(async value=>value);mocks.more.mockResolvedValue(examples);});
afterEach(cleanup);
async function open(){render(<UnderstandHelp sentence="Try again." portuguese="Tente novamente." deckId="deck" open/>);fireEvent.click(screen.getByRole('button',{name:'Try'}));fireEvent.click(screen.getByRole('button',{name:'Explicar “Try”'}));await screen.findByText('Exemplos para praticar');}
it('retains the usage note',()=>{expect(splitExplanation(explanation.explanation).body).toContain('👉 tried');});
it('shows five addable examples without the original sentence',async()=>{await open();expect(screen.queryByText('Try again.')).toBeNull();expect(screen.getAllByRole('button',{name:'Adicionar como cartão'})).toHaveLength(5);});
it('creates a situation and removes it from suggestions',async()=>{await open();fireEvent.click(screen.getAllByRole('button',{name:'Adicionar como cartão'})[0]);await waitFor(()=>expect(screen.getAllByRole('button',{name:'Adicionar como cartão'})).toHaveLength(4));const [deck,front,back]=mocks.add.mock.calls[0];expect(deck).toBe('deck');expect(readSituation(front,back)?.english).toBe('Try this.');});
it('rejects punctuation variants and replenishes to five',async()=>{const generate=vi.fn().mockResolvedValueOnce([{english:'TRY AGAIN!',portuguese:'Tente'},...examples.slice(0,3)]).mockResolvedValueOnce(examples);expect(await fiveNewExamples([],['Try again.'],generate)).toHaveLength(5);expect(generate).toHaveBeenCalledTimes(2);});
it('does not accept incomplete batches',async()=>{const generate=vi.fn().mockResolvedValue(examples.slice(0,1));await expect(fiveNewExamples([],[],generate)).rejects.toThrow('cinco');expect(generate).toHaveBeenCalledTimes(3);});
it('excludes another existing card from initial options',async()=>{mocks.cards.mockResolvedValue([{...buildSituationHtml({...examples[0],context:'',mediaHtml:''})}]);mocks.more.mockResolvedValue([...examples.slice(1),{english:'We can try tomorrow.',portuguese:'Podemos tentar amanhã.'}]);await open();expect(screen.queryByText('Try this.')).toBeNull();expect(screen.getAllByRole('button',{name:'Adicionar como cartão'})).toHaveLength(5);});
it('adds five more and excludes previous examples',async()=>{await open();const next=examples.map(item=>({english:'Please '+item.english,portuguese:item.portuguese}));mocks.more.mockResolvedValue(next);fireEvent.click(screen.getByRole('button',{name:'Gerar mais exemplos'}));await screen.findByText(next[0].english);expect(screen.getAllByRole('button',{name:'Adicionar como cartão'})).toHaveLength(10);expect(mocks.more.mock.calls.at(-1)?.[2]).toEqual(expect.arrayContaining(examples.map(item=>item.english)));});
